# Generated by Django 4.0.3 on 2022-03-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0002_profile_delete_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
