# Generated by Django 4.0.3 on 2022-03-12 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restro', '0004_category_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('meal', models.CharField(max_length=1000, null=True)),
                ('quantity', models.CharField(blank=True, max_length=5, null=True)),
                ('price', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('state', models.CharField(max_length=500, null=True)),
                ('mobile_no', models.CharField(max_length=13, null=True)),
                ('zipcode', models.CharField(max_length=6, null=True)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Scheduled', 'Scheduled'), ('Shipped', 'Shipped'), ('In Progress', 'In Progress')], default='In Progress', max_length=500)),
                ('deliver_date', models.DateTimeField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
