# Generated by Django 4.0.3 on 2022-03-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
