# Generated by Django 4.0.3 on 2022-03-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
